---
# ***IMPORTANTE***
# Ajude a equipe que trabalhou neste bot para você poder descansar sem pagar mensalidade mensalidade, doando bnb, busd, bcoin, spg ou spe. 
# Com seu incentivo podemos seguir melhorando o bot e criando novas ferramentas. 

  # Valores de configuração do bot
  ship_settings:
    # Quantidade total de naves (total)
    empty_qtd_spaceships: 150
    
    # Quantas naves deseja entrar para o boss
    qtd_send_spaceships: 15

    # Se deseja dar surrender, alterar para o numero do boss que você deseja parar, para deixar a execução infinita deixe com zero.
    boss_surrender: 0
    
    # Envia somente naves 100% deixe com valor True e False para as mais carregadas
    send_ships_full: True

    # Se desejar que remova as naves antes de adicionar outras deixe com True e False para manter as que tem vida.
    remove_ships: False 

    # Volta para a spaceship nas waves 9, 11, 14, 16, 19 e 21
    key_waves: True
    
  # Valor de confiança das comparações
  threshold:
    # Valor padrão: 0.7
    default: 0.7

    # Valor padrão: 0.8
    commom: 0.8
    
    # Valor padrão 0.9
    hard: 0.9

    # Valor padrão: 0.8
    select_wallet_buttons: 0.8

    # Valor padrão: 0.9
    go-fight: 0.9

    # Valor padrão: 0.9
    green_bar: 0.95

    # Valor padrão 0.98
    15-15-ships: 0.98

    # Valor padrão 0.95
    0-15: 0.95